---
title: "Untitled"
format: html
editor: visual
---

# 1. Import packages

```{r}
library(dplyr)
library(ggplot2)
library(tidyverse)
library(tidyr)
library(lme4)
library(ggeffects)

```

# 2. GROWTH DATA

## 2.1. Import data sets

```{r}

## Import the scale readings datasets of each year and each reader

iServ2021A <- read.csv("data/raw/iserv2021Raphael.csv", sep = ";")
iServ2021B <- read.csv("data/raw/iserv2021Valérie.csv", sep = ";")
iServ20221 <- read.csv("data/raw/iserv2022Raphael.csv", sep = ";")
iServ2022B <- read.csv("data/raw/iserv2022Valérie.csv", sep = ";")
iServ2023 <- read.csv("data/raw/iserv2023Raphael.csv", sep = ";")

## Import the dataset of the double blind reading test

ObservatorData <- read.csv("data/raw/ObservatorCorrection.csv", sep = ";")

```

## 2.2 Clean growth data

```{r}

GrowthDataTotal <- bind_rows(
  iServ2021A,
  iServ2021B,
  iServ20221,
  iServ2022B,
  iServ2023)%>%
  mutate(
    Sex = as.factor(Sex),
    Origin = as.factor(Origin))%>%
  select(1, 7, 10, 11:17, 6, 3) %>%
  pivot_longer(
    cols = starts_with("L"),
    names_to = "Age",
    values_to = "Length") %>%
  filter(Age != "LT") %>%
  mutate(
    Age = str_remove(Age, "L") %>% as.numeric(),
    CaptureYear = as.numeric(CaptureYear)) %>%
  filter(!is.na(Length)) %>%
  mutate(
    StockingYear = CaptureYear - Age,
    CaptureYear = case_when(
      CaptureYear == 2021 ~ "FirstYear",
      CaptureYear == 2022 ~ "SecondYear",
      CaptureYear == 2023 ~ "ThirdYear",
      TRUE ~ as.character(CaptureYear)))

```

## 2.3 Double observator correction

```{r}

CorrectionData <- ObservatorData %>% 
  select(1,7,9:16)%>%
  pivot_longer(
    cols = starts_with("L"),
    names_to = "FishAge",
    values_to = "Length")%>%
  mutate(
    FishAge = str_remove(FishAge, "L"),
    FishAge = factor(FishAge)) %>%
  filter(!is.na(Length),
         FishAge != "T")


## Filter the data by origin
NaturalData <- CorrectionData %>% filter(Origin == "Natural")
PuyaData    <- CorrectionData %>% filter(Origin == "Puya")
RivesData   <- CorrectionData %>% filter(Origin == "Rives")


## Model for Natural
ModelNatural <- lmer(Length ~ FishAge * Reader + (1 | Id), data = NaturalData)
summary(ModelNatural)
PredictionNatural <- ggpredict(ModelNatural, terms = c("FishAge", "Reader"))

ggplot(PredictionNatural, aes(x = x, y = predicted, color = group)) +
  geom_line(linewidth = 1.2) +
  geom_point(size = 3) +
  labs(
    x = "Fish age",
    y = "Predicted scale length",
    color = "Observer") +
  theme_classic()

BiasNatural <- tibble(
  Age = c("1","2","3","4","5"),
  Bias = -c(
    fixef(ModelNatural)["ReaderValerie"],
    fixef(ModelNatural)["ReaderValerie"] + fixef(ModelNatural)["FishAge2:ReaderValerie"],
    fixef(ModelNatural)["ReaderValerie"] + fixef(ModelNatural)["FishAge3:ReaderValerie"],
    fixef(ModelNatural)["ReaderValerie"] + fixef(ModelNatural)["FishAge4:ReaderValerie"],
    fixef(ModelNatural)["ReaderValerie"] + fixef(ModelNatural)["FishAge5:ReaderValerie"]),
  Origin = "Natural")


## Model for Rives
ModelRives <- lmer(Length ~ FishAge * Reader + (1 | Id), data = RivesData)
summary(ModelRives)
PredictionRives <- ggpredict(ModelRives, terms = c("FishAge", "Reader"))

ggplot(PredictionRives, aes(x = x, y = predicted, color = group)) +
  geom_line(linewidth = 1.2) +
  geom_point(size = 3) +
  labs(
    x = "Fish age",
    y = "Predicted scale length",
    color = "Observer"
  ) +
  theme_classic()

BiasRives <- tibble(
  Age = c("1","2","3","4","5"),
  Bias = -c(
    fixef(ModelRives)["ReaderValerie"],
    fixef(ModelRives)["ReaderValerie"] + fixef(ModelRives)["FishAge2:ReaderValerie"],
    fixef(ModelRives)["ReaderValerie"] + fixef(ModelRives)["FishAge3:ReaderValerie"],
    fixef(ModelRives)["ReaderValerie"] + fixef(ModelRives)["FishAge4:ReaderValerie"],
    fixef(ModelRives)["ReaderValerie"] + fixef(ModelRives)["FishAge5:ReaderValerie"]),
  Origin = "Rives")%>%
  mutate(
    Bias = if_else(Age == "5" & is.na(Bias), -195.239153, Bias))


## Model for la Puya
ModelPuya <- lmer(Length ~ FishAge * Reader + (1 | Id), data = PuyaData)
summary(ModelPuya)
PredictionPuya <- ggpredict(ModelPuya, terms = c("FishAge", "Reader"))

ggplot(PredictionPuya, aes(x = x, y = predicted, color = group)) +
  geom_line(linewidth = 1.2) +
  geom_point(size = 3) +
  labs(
    x = "Fish age",
    y = "Predicted scale length",
    color = "Observer"
  ) +
  theme_classic()

BiasPuya <- tibble(
  Age = c("1","2","3","4","5"),
  Bias = -c(
    fixef(ModelPuya)["ReaderValerie"],
    fixef(ModelPuya)["ReaderValerie"] + fixef(ModelPuya)["FishAge2:ReaderValerie"],
    fixef(ModelPuya)["ReaderValerie"] + fixef(ModelPuya)["FishAge3:ReaderValerie"],
    fixef(ModelPuya)["ReaderValerie"] + fixef(ModelPuya)["FishAge4:ReaderValerie"],
    fixef(ModelPuya)["ReaderValerie"] + fixef(ModelPuya)["FishAge5:ReaderValerie"]),
  Origin = "Puya")
  

BiasByOrigin <- bind_rows(BiasNatural, BiasRives, BiasPuya)%>%
  mutate(Age = as.numeric(Age))

```

## 2.4. Write new file

```{r}
GowthDataRaphael <- GrowthData %>% filter(Reader == "Raphael")
GrowthDataValerie <- GrowthData %>% filter(Reader == "Valerie")

GrowthDataRaphael <- GowthDataRaphael %>%
  left_join(BiasByOrigin, by = c("Origin", "Age")) %>%
  mutate(Length_corrected = Length - Bias)%>%
  select(1:6,10,8)%>%
  rename(Length = Length_corrected)

CorrectedGrowthData <- bind_rows(GrowthDataRaphael, GrowthDataValerie) %>%
  arrange(Origin, Id, Age)

write.csv(CorrectedGrowthData,
          file = "data/processed/corrected_growth_data.csv",
          row.names = FALSE)
```

# 3. Genetic data
